# Generated by Django 4.0.1 on 2022-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('associates', models.IntegerField()),
                ('shift_length', models.IntegerField()),
                ('start_date', models.DateField()),
                ('horizon', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
